version: "3.3"

services:
  hcapp:
    image: nginx:latest
    volumes:
      - ./hcapp/public_html:/usr/share/nginx/html
      - ./hcapp/nginx:/etc/nginx/conf.d
    ports:
      - "80"

  hcprx:
    image: nginx:latest
    volumes:
      - ./hcprx/nginx:/etc/nginx/conf.d
    ports:
      - "80"

  prx:
    image: nginx:latest
    volumes:
      - ./prx/nginx:/etc/nginx/conf.d
    ports:
      - "80"

  cf:
    image: nginx:latest
    volumes:
      - ./cf/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
