version: "3.3"

services:
  lb:
    image: nginx:latest
    volumes:
      - ./services/lb/nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
  
  frontend:
    image: nginx:latest
    volumes:
      - ./services/frontends/nginx/:/etc/nginx/conf.d
    ports:
      - "80"

  backend:
    image: nginx:latest
    volumes:
      - ./services/backends/nginx/:/etc/nginx/conf.d
    ports:
      - "80"

