version: "3.3"

services:
  lb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./services/lb/nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./services/frontends/nginx/:/etc/nginx/conf.d
    ports:
      - "80"

  backend:
    image: nginx:latest
    volumes:
      - ./services/backends/nginx/:/etc/nginx/conf.d
      - ./services/backends/public_html:/usr/share/nginx/html
    ports:
      - "80"

